'use strict';
const width = 10;
const height = 50;
const area = width * height;
console.log(`value of area: ${area}`);
console.log(`typeof area: ${typeof area}`);
const bill = 20;
const payment = 30;
const change = payment - bill;
console.log(`value of change: ${change}`);
console.log(`typeof change: ${typeof change}`);
const quizzes = 5;
const midterm = 10;
const final = 20;
const grade = (quizzes + midterm + final) / 3;
console.log(`value of grade: ${grade}`);
console.log(`typeof grade: ${typeof grade}`);
const firstName = 'Ben';
const lastName = 'Imberman';
const fullName = `${firstName} ${lastName}`;
console.log(`value of fullName: ${fullName}`);
console.log(`typeof fullName: ${typeof fullName}`);
const pH = 8;
const isAcidic = pH < 7;
console.log(`value of isAcidic: ${isAcidic}`);
console.log(`typeof isAcidic: ${typeof isAcidic}`);
const headCount = 300;
const isSparta = headCount === 300;
console.log(`value of isSparta: ${isSparta}`);
console.log(`typeof isSparta: ${typeof isSparta}`);
const motto = fullName + ' is the GOAT';
console.log(`value of motto: ${motto}`);
console.log(`typeof motto: ${typeof motto}`);
